# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

build:
  # https://github.com/Shippable/support/issues/3873
  pre_ci_boot:
      # image_name: drydock/u14pytall
      image_tag: v5.8.2
  ci:
    - echo $CI_REPORTS && mkdir -p $CI_REPORTS
    - echo $COVERAGE_REPORTS && mkdir -p $COVERAGE_REPORTS

env:
  global:
    - CI_REPORTS=shippable/testresults
    - COVERAGE_REPORTS=shippable/codecoverage
    - DISPLAY=""

language: python

sudo: true

python:
  - 2.7
  - 3.5

cache: pip

before_install:
  - apt-get update # --fix-missing
  - apt-get install freetype*
  - apt-get install python-dev python-tk python3-tk
  - apt-get install pkg-config
  - pip install --upgrade pip wheel

install:
  - root=$PWD
  - mkdir libs

  - pip install -r requirements.txt
  - pip install "nose>=1.3.7" coverage codecov "pytest>=3.0.5" flake8

script:
  - mkdir mkdir output && mkdir results
  - gcc --version ; python --version ; pip --version ; pwd ; ls -l
  - python setup.py build_ext --inplace

  # - nosetests -v --with-xunit --xunit-file=$CI_REPORTS/nosetests.xml
  - nosetests -v --exe --with-doctest --with-xunit --with-coverage --cover-package=imsegm --xunit-file=$CI_REPORTS/nosetests.xml
  - python setup.py check -m -s
  - flake8 . --ignore=E402,E731 --max-line-length=100

after_success:
  - python setup.py install

  - coverage xml -o $COVERAGE_REPORTS/coverage.xml
  - codecov  # public repository on Travis CI
  - coverage report

  - cd .. && python -c "import imsegm.descriptors"
