version: 2.0

references:

  install_pips: &install_pips
    run:
      name: Install PyPI dependences
      command: |
        sudo apt-get update -qq
        #sudo apt-get install git-lfs
        sudo apt-get install tk-dev pkg-config python-dev python-tk
        sudo pip install --upgrade pip setuptools
        sudo pip install -r ./tests/requirements.txt
        sudo pip install -U backports.functools_lru_cache  # required for matplotlib @py2
        pip install -r requirements.txt --user
        pip --version ; pip list

  test_coverage: &test_coverage
    run:
      name: Testing and coverage
      command: |
        unset DISPLAY
        mkdir output && mkdir results && mkdir test-reports
        coverage run --source imsegm -m pytest imsegm tests -v --junitxml=test-reports/pytest_junit.xml
        coverage report
        python setup.py check --metadata --strict

  build_project: &build_project
   run:
     name: Building project
     command: |
       pip install cython
       gcc --version
       python --version
       python setup.py build_ext --inplace
       pwd ; ls -l imsegm

  make_docs: &make_docs
   run:
     name: Make Documentation
     command: |
       sudo apt-get install pandoc
       pyenv global 3.7.3
       python --version
       pip install -r requirements.txt
       pip install -r docs/requirements.txt
       python setup.py build_ext --inplace
       # sphinx-apidoc -o ./docs/source ./imsegm **/test_* --force --follow-links
       cd docs
       make html --debug --jobs 2 SPHINXOPTS="-W"
       make latexpdf

jobs:

  Py3-Tests:
    docker:
      - image: circleci/python:3.6
    steps: &steps_test
      - checkout
      # INSTALLATION
      - *install_pips
      #- run: git lfs pull
      # BUILDING
      - *build_project
      # TESTING
      - *test_coverage

      # PASSING
      - run:
          name: Finalise
          command: |
            python setup.py install --user
            coverage report
            coverage xml -o test-reports/coverage.xml

      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  Build-Docs:
    docker:
      - image: readthedocs/build:latest
    steps:
      - checkout
      # BUILDING
      - *build_project
      # DOCUMENTATION
      - *make_docs
      # PREVIEW
      - store_artifacts:
          # allows us to preview the generated html pages
          path: docs/build/html/
          destination: html

workflows:
  version: 2
  build:
    jobs:
      - Py3-Tests
      # - Build-Docs
