name: Install pkg

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  - push
  - pull_request

jobs:
  pkg-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependenies
        run: |
          pip install --upgrade cython setuptools wheel check-manifest twine==3.2

      - name: Check package
        run: |
          check-manifest
          python setup.py check --metadata --strict
          python setup.py build_ext --inplace
          python setup.py install --dry-run --user

      - name: Create package
        run: |
          python setup.py sdist

      - name: Verify package
        run: |
          twine check dist/*
          python setup.py clean

  pkg-install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15]  # , windows-2019
        python-version: [3.7]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create package
        run: |
          python setup.py sdist

      - name: Install package
        run: |
          pip install virtualenv
          virtualenv vEnv
          source vEnv/bin/activate
          pip install dist/*
          cd .. & python -c "import imsegm ; print(imsegm.__version__)"
          deactivate
          rm -rf vEnv
