name: Install pkg

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches: [ master ]
  pull_request: { }

jobs:
  pkg-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependenies
        run: |
          pip install --upgrade cython "setuptools>=42" wheel check-manifest "twine==3.2"

      - name: Check package
        run: |
          check-manifest
          python setup.py check --metadata --strict
          python setup.py build_ext --inplace
          python setup.py install --dry-run --user

      - name: Create package
        run: |
          python setup.py sdist bdist_wheel

      - name: Verify package
        run: |
          twine check dist/*
          python setup.py clean

  pkg-install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create package
        run: |
          pip install cython setuptools wheel
          python setup.py sdist bdist_wheel

      - name: Install package
        working-directory: ./dist
        run: |
          pip install $(python -c "import glob ; pkg = glob.glob('*.whl')[0] ; print(pkg)")
          python -c "import imsegm ; print(imsegm.__version__)"
